spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=macneo4j


# For SchemaRepository: Make sure the graph database name is correct
# usually graph.db or neo4j. Make sure it is the same as the database 
# used in the above neo4j.uri!
#spring.data.neo4j.database=neo4j
spring.data.neo4j.database=graph.db

logging.level.org.springframework.data.neo4j=DEBUG

clientUrl=http://localhost:4200

# The following is copied from content-service
#The bean 'lazyFetchAspect', defined in graph core Main.class
spring.main.allow-bean-definition-overriding=true

# This is used to avoid exporting null in JSON. See 
# https://docs.spring.io/spring-boot/docs/1.5.x/reference/html/howto-spring-mvc.html#howto-customize-the-jackson-objectmapper
# and https://stackoverflow.com/questions/51261809/spring-boot-jackson-non-null-property-not-working
# Apparently the following cannot work reliably. Follow the example to use a class level configuration.
#spring.jackson.default-property-inclusion=NON_NULL

# Used to fetch pubmed detailed information
pubmedUrl1=https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&retmode=xml&id=
pubmedUrl2=

## Used to persist instances worked by curators
file_repo_dir=/Users/wug/git/reactome/curator-tool-ws/file_repo
#
## Used for handling pathway diagrams
diagram_graph_dir=/Users/wug/Documents/web_curator_tool/diagram/graph
diagram_cytoscape_dir=/Users/wug/Documents/web_curator_tool/diagram/cytoscape

# The following configurations are for test at aws_curator by running springboot as a standalone app.
# Note: The test neo4j password at aws_curator
#spring.neo4j.authentication.password=linuxneo4j
#file_repo_dir=/home/gwu/curator-tool-ws/file_repo
#diagram_graph_dir=/home/gwu/curator-tool-ws/diagram/graph
#diagram_cytoscape_dir=/home/gwu/curator-tool-ws/diagram/cytoscape

server.port=9090

# Used to manage the user database in an embedded h2 database
# Make sure this is changed at the server: There is no need to change this. Just make sure
# the files in data are copied to the server.
#spring.datasource.url=jdbc:h2:file:./data/reactome_h
# Don't lock the file so that we can test at local dev
spring.datasource.url=jdbc:h2:file:./data/reactome_h2;DB_CLOSE_DELAY=-1;FILE_LOCK=NO
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=reactome
spring.datasource.password=web_tool_h2_er
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
# JPA (Hibernate) configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
