spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=pR0d@ct2

logging.level.org.springframework.data.neo4j=DEBUG

# The following is copied from content-service
#The bean 'lazyFetchAspect', defined in graph core Main.class
spring.main.allow-bean-definition-overriding=true

# This is used to avoid exporting null in JSON. See 
# https://docs.spring.io/spring-boot/docs/1.5.x/reference/html/howto-spring-mvc.html#howto-customize-the-jackson-objectmapper
# and https://stackoverflow.com/questions/51261809/spring-boot-jackson-non-null-property-not-working
# Apparently the following cannot work reliably. Follow the example to use a class level configuration.
#spring.jackson.default-property-inclusion=NON_NULL

